### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by respectTheCode** [Apercu/react-native-zeroconf#1]
Is android support something you plan to add?

**Comment by Apercu** [comment]
Hi, this is something I plan indeed, but I don't have an android terminal (yet) and the emulator is really annoying to use, so I just dunno when.

I'm open to PR though ;)

**Comment by iheart2code** [comment]
Perhaps I can take a stab at this as well. I know Android, but am not really sure how to add Android to a React Native plugin. I'll let you know if I get stuck.
