### ISSUE TITLE
unhandled exception when services are removed

### ISSUE THREAD

**Issue by guptaash** [Apercu/react-native-zeroconf#10]
Seems like a small bug -

DeviceEventEmitter.addListener('RNZeroconfRemove', service => {
      if (!service || !service.name) { return }
      const { name } = service

      delete this.services[name]  <--- this should be _services

      this.emit('remove', name)
      this.emit('update')
    })

**Comment by Apercu** [comment]
Thanks, sorry about that, this should not have happened.

**Comment by Apercu** [comment]
The fix is now available on npm as the 0.3.1 release
