### ISSUE TITLE
Build error on Android

### ISSUE THREAD

**Issue by luisfpinto** [Apercu/react-native-zeroconf#15]
I'm trying to compile my app for android with this package and I get an error. So I was wondering if this package maybe isn't compatible.

**Comment by Apercu** [comment]
It should, but without knowing said error I'm afraid I can't really help ;)

**Comment by luisfpinto** [comment]
This is the error I get :

```
MainActivity.java:4: error: cannot find symbol
import com.balthazargronon.RCTZeroconf.ZeroconfReactPackage;
                                      ^
  symbol:   class ZeroconfReactPackage
  location: package com.balthazargronon.RCTZeroconf

MainActivity.java:42: error: cannot find symbol
            new ZeroconfReactPackage(),
                ^
  symbol:   class ZeroconfReactPackage
  location: class MainActivity
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

```

**Comment by Apercu** [comment]
Could you please describe the steps you did for installation?

**Comment by luisfpinto** [comment]
Yes sure, I did:

```
npm i -S react-native-zeroconf
rnpm link react-native-zeroconf
```

Then I get: 
> rnpm-link info Linking react-native-zeroconf android dependency 
rnpm-link info Android module react-native-zeroconf has been successfully linked 
rnpm-link info iOS module react-native-zeroconf is already linked

Then I include this on my code like this: 
`
import Zeroconf from 'react-native-zeroconf'`

So I run on my devices as:

```
adb reverse tcp:8081 tcp:8081
react-native run-android 
```

And finally while it is building the app I get the error I told you before: 

```
:app:compileDebugJavaWithJavac
.../android/app/src/main/java/com/nmy_app/MainActivity.java:4: error: cannot find symbol
import com.balthazargronon.RCTZeroconf.ZeroconfReactPackage;
                                      ^
  symbol:   class ZeroconfReactPackage
  location: package com.balthazargronon.RCTZeroconf
.../android/app/src/main/java/com/my_app/MainActivity.java:42: error: cannot find symbol
            new ZeroconfReactPackage(),
                ^
  symbol:   class ZeroconfReactPackage
  location: class MainActivity
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 3.161 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by Apercu** [comment]
Thanks for the insights! Could you please check that each step of the [manual installation steps](https://github.com/Apercu/react-native-zeroconf/wiki) for Android have been done correctly by rnpm? I'm guessing there is something missing from here.

I don't have a lot of experience in Android but we can ping the generous contributor who did the Android part if your search is fruitless.

**Comment by luisfpinto** [comment]
Look like everything is correct

**Comment by Apercu** [comment]
Hi @iheart2code!

Would you mind taking a look at it?

**Comment by iheart2code** [comment]
Not sure when I can get to this. Possibly sometime tomorrow.

**Comment by faireroquen** [comment]
I have "package com.balthazargronon.react;" in ZeroconfModule.java and ZeroconfReactPackage.java.
Renaming to "package com.balthazargronon.RCTZeroconf;" and the app compile.

But now for me , i have 
Cannot read property 'scan' of undefined when i try to call the scan method but console.log(zeroconf.scan) return that the function exists : 
scan()
{var type=arguments.length<=0||arguments[0]===undefined?'http':arguments[0];var protocol=arguments.length<=1||arguments[1]===undefined?'tcp':arguments[1];var domain=arguments.length<=2…

**Comment by faireroquen** [comment]
My bad , I'm still a beginner in react native ,  the package was not registred.
I add  new ZeroconfReactPackage() on getPackages() method of my app : MainApplication.java
For now , i get no errors.

**Comment by Apercu** [comment]
Thanks then @faireroquen! I will push your patch now.

**Comment by Apercu** [comment]
Would @luisfpinto or @faireroquen mind switching to the `fix-android-package` to check if everything is correct?

**Comment by faireroquen** [comment]
I'm not sure i'm doing it right: 
I do : npm install -S git://github.com/Apercu/react-native-zeroconf.git#fix-android-package
but now i got  ExceptionsManager.js:61Requiring unknown module "react-native-zeroconf".If you are sure the module is there, try restarting the packager or running "npm install"

i restart the packager but nothing change

**Comment by Apercu** [comment]
Could you please retry now?

**Comment by faireroquen** [comment]
Still the same. :(

**Comment by Apercu** [comment]
Have you `rnpm link react-native-zeroconf` after?

**Comment by faireroquen** [comment]
Yes , but it says that its allready linked , i tried with a new fresh project but still the same.

**Comment by Apercu** [comment]
That's so strange, I only did the rename you specified. Can you check if you indeed have the change and it's correct?

**Comment by faireroquen** [comment]
All changes are there , i have the module in node_modules/. Everything looks good.
Maybe react native does not like modules from git repositories branch, don't really know about that.

Or , and i've just see that , the path of the android module is not good , i have com/balthazargronon/react and it should be com/balthazargronon/RCTZeroconf

**Comment by Apercu** [comment]
Yes, that's what I did on [the first commit](https://github.com/Apercu/react-native-zeroconf/commit/6de402ccae5e592df9ff6fcb2edae6a26ac1a16c), but tried another thing afterwards since you told me it didn't work, since I was unsure you did the folder rename. I can try to push an rc version on npm so you can test it out

**Comment by faireroquen** [comment]
Yes , try to push a npm version and i'll try it :+1:

**Comment by Apercu** [comment]
Pushed the `0.5.1-rc.1` version!

**Comment by faireroquen** [comment]
It works :+1:

**Comment by Apercu** [comment]
Cool! Gonna merge this on develop.

**Comment by Apercu** [comment]
@luisfpinto Feels free to reopen this if the problem persist with the `0.5.2` release
