### ISSUE TITLE
index.android.bundle:24239 Cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by mathieu-gosbee-connectedlab** [Apercu/react-native-zeroconf#16]
From my investigation, ```const RNZeroconf = NativeModules.RNZeroconf``` is not defined

**Comment by Apercu** [comment]
Which version? Did your `rnpm link`?

**Comment by pranavrajs** [comment]
@mathieu-gosbee-connectedlab Got the same issue while running on android. @Apercu `rnpm link` didn't work. I tried manual install , worked correctly. My RN version is 0.35.0

**Comment by mathieu-gosbee-connectedlab** [comment]
Please note rnpm doesn't exist anymore. You have to run ```react-native install react-native-zeroconf``` and then ```react-native link react-native-zeroconf```

**Comment by pellepersson** [comment]
I had the same issue. Running RN 0.39. 

Running `react-native install react-native-zeroconf` and then `react-native link react-native-zeroconf` did not help, but following the guide for manual installation and adding what was missing solved the issue.

**MainApplication.java** was missing
`import com.balthazargronon.RCTZeroconf.ZeroconfReactPackage;`
and

`new ZeroconfReactPackage()` in the **getPackages()** method
