### ISSUE TITLE
unable to resolve module

### ISSUE THREAD

**Issue by JeroenNelen** [Apercu/react-native-zeroconf#19]
Hello Apercu,

I'm trying to get it to work following the steps in the readme.doc.
However, as soon as I try to run it, I get the following error message:
Android:

    Requiring unknown module "react-native-zeroconf". If you are sure the module is there, try restarting the packager or running "npm install".

iOS:

    Unable to resolve module react-native-zeroconf from ...: Module does not exist in the module map or in these directories ...link to npm folder

I see there is no index.js in the main folder of this npm package and I'm trying to import it as follows:

    import Zeroconf from 'react-native-zeroconf';

I'm not using webpack, just running via

    "start": "node node_modules/react-native/local-cli/cli.js start",

I have a .babelrc file with

    {
      "presets": ["react-native"]
    }

Do you have any idea what might be causing this issue or what I am doing wrong?

Kind regards,

**Comment by Apercu** [comment]
Hey,

How did you install the module?

**Comment by JeroenNelen** [comment]
Hey Apercu,

Thanks for your swift reply.
I installed as suggested in the readme.md:
`npm i -S react-native-zeroconf
react-native install react-native-zeroconf
react-native link react-native-zeroconf`

I have currently switched from version 0.5.3 to 0.3.1 and installed the same way:
`npm i -S react-native-zeroconf
react-native install react-native-zeroconf
react-native link react-native-zeroconf`

And at first sight, it seems to work for Android (not for iOS) that way.
I don't get the errors about unresolved module anymore. But in 0.3.1 it also has the Zeroconf.js in the root file (and like I mentioned, for 0.5.3 there is no .js file in the root folder...).

Kind regards,

**Comment by Apercu** [comment]
The sources are not pushed to npm, but the compiled script is located in the `dist` folder, check if it's here but it should be.

Do you mind giving some insights on this @mathieu-gosbee-connectedlab? I know you installed it successfully not so long ago.

You might want to give a shot at the [manual installation wiki](https://github.com/Apercu/react-native-zeroconf/wiki) in the meantime.

**Comment by mathieu-gosbee-connectedlab** [comment]
react-native install react-native-zeroconf?

**Comment by westcode** [comment]
It seems the src package (no dist folder)  is in npm, i just downloaded the package and this is the result in the node_modules folder: 
![root](https://cloud.githubusercontent.com/assets/5854357/19891678/77a78f6e-a041-11e6-9872-33231b9a2f36.png)

**Comment by Apercu** [comment]
Stupid error on my part, sorry about that. This should be good in 0.5.4. Thanks @westcode.

**Comment by JeroenNelen** [comment]
Hey @Apercu,

Sorry for my late reply, the dist was indeed missing, I got it to work by manually running npm i in the node_modules folder of the zeroconf and then running the build command to generate the dist folder.

Kind regards,
