### ISSUE TITLE
Return more than just the host name in found event

### ISSUE THREAD

**Issue by iheart2code** [Apercu/react-native-zeroconf#2]
I would propose you return a similar object to what [node-mdns](https://github.com/agnat/node_mdns) is returning.

Example:
![example](https://cloud.githubusercontent.com/assets/590310/12179751/7a263fec-b52d-11e5-97c8-77db85c3d709.png)

**Comment by Apercu** [comment]
Yeah definitely, will change that soon!

**Comment by iheart2code** [comment]
@Apercu I can do the work for this and submit a PR. I'd ask that you first provide a permissive license for the project, though. See issue #3.
