### ISSUE TITLE
Finding computers in the network

### ISSUE THREAD

**Issue by Unforgiven-wanda** [Apercu/react-native-zeroconf#25]
Hello,
this is not an issue per se, but seeing as there is no usage example for your module, I've taken the liberty to open one.

I'd like to know if this module allows scanning the local network to discover the computers that are connected to it themselves, displaying their IPs and possibly their names. The readme is not clear on this point.

Thank you for taking the time.
Good evening.

**Comment by Apercu** [comment]
This module is, thus its name, resolving services that advertise themselves using the [zeroconf](https://en.wikipedia.org/wiki/Zero-configuration_networking) protocol. You should read a bit on it to understand fully 😃
