### ISSUE TITLE
TransformError when importing Zeroconf

### ISSUE THREAD

**Issue by josvos** [Apercu/react-native-zeroconf#26]
Hi,

Using react-native 0.40.0 on Android and react-native-zeroconf 0.5.6, I get the following error when doing `import Zeroconf from 'react-native-zeroconf'` (I don't even use it yet...):

```
TransformError: /home/jos/proj/test/rntest/node_modules/react-native-zeroconf/dist/index.js: __DEV__ is not defined (While processing preset: "/home/jos/proj/test/rntest/node_modules/react-native/Libraries/react-native/react-native.js")
```

I get this error when running in development mode (using the app-debug.apk) in the red popup screen, as well as when buidling a release version.

**Comment by Apercu** [comment]
https://github.com/facebook/react-native/issues/7814 ?

**Comment by josvos** [comment]
I don't have a `.babelrc` file, removed that for an earlier problem already.

In the meantime I'm at react-native 0.41.1, node_modules freshly installed (I do that every month or so), and the problem with react-native-zeroconf (now at 0.6.0) persists.

**Comment by Apercu** [comment]
Do you have an example repo I could look into? Could be easier to debug

**Comment by josvos** [comment]
I wanted to make a clean base tree, but when I init a new RN project, add r-n-zeroconf to the index.android.js file and there even create a Zeroconf object and start a scan (although I do not get results, I see a multicast message being sent) there is no TransformError :-(.  Still no idea what's causing the problem, the npm modules in both node_modules are at the latest version.

**Comment by Apercu** [comment]
Hum, that's weird, are you using webpack or something in your other project?

**Comment by josvos** [comment]
No... well, it has to be caused by something... I now added all npm modules I use in my main project to the minimal project tree and imported something from each module in index.android.js, with no success: that is, I can't reproduce it yet in the new tree.

**Comment by Apercu** [comment]
Closing this, reopen if you find the issue and is related to the project.
