### ISSUE TITLE
On scan start app freezes

### ISSUE THREAD

**Issue by nomoreboredom** [Apercu/react-native-zeroconf#27]
Hello,

I have a situation like this. I use zeroconf as the following in my app:

    import Zeroconf from 'react-native-zeroconf'
        ...
        constructor (props) {
            super(props)
            this.state = initialState
            this._zeroconf = new Zeroconf() 
        }
and then on componentDidMount:

     this._zeroconf.scan()

When I call the scan function (I have tried with parameters as well), my app freezes. a couple of times I was able to see an error message:

     Starting service discovery failed with code:0

Any idea what may be causing this? Thanks! I am using RN@0.39 if that means anything.

**Comment by Apercu** [comment]
Hey

Hum no that's strange, never experienced the issue, and the scan should happen in another process anyway, will keep this open.

**Comment by nomoreboredom** [comment]
Wow weirdest things of all. I needed to restart my handy for it. Not restarting the packager, needed really to restard my Asus 4.4.2. I am closing this issue now, thanks again for this lib :)

**Comment by Apercu** [comment]
Glad to hear that! Thanks 😄
