### ISSUE TITLE
Duplicate interface definition for class RCTBridge - React 0.40

### ISSUE THREAD

**Issue by jamsesso** [Apercu/react-native-zeroconf#28]
Hi,
On a React Native 0.40 project, installing and linking this project results in the following error on iOS: "Duplicate interface definition for class RCTBridge" when attempting to build.

After some Googling, I found that as of React Native 0.40 the imports need to be declared as `#import <React/RCTBridge.h>` instead of `#import "RCTBridge.h"`. I believe the fix is as easy as renaming the imports! Link: https://github.com/facebook/react-native/issues/11725

Note that I haven't attempted to run this on Android yet, so I am not sure if there are similar issues on that platform.

**Comment by Apercu** [comment]
Thanks for this, I believe you're right, changing the headers should be all we need

**Comment by kartikeygupta-tudip** [comment]
Hey, @jamsesso  thanks for this solution it worked for me as I am using react-native version above 0.40.
