### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by iheart2code** [Apercu/react-native-zeroconf#3]
As it stands, this library technically can't be used/extended by others. Please consider licensing this library, preferably under Apache V2 or MIT.

**Comment by Apercu** [comment]
The License is MIT, you can see it in the `package.json`, I dunno if I still have to put an explicit `LICENSE` file though

**Comment by iheart2code** [comment]
I'd put it in the LICENSE file and/or in the README. You'll also need to include it in the header of your Objective-C files.

**Comment by iheart2code** [comment]
Thanks!
