### ISSUE TITLE
Discovering a Node Http Server

### ISSUE THREAD

**Issue by brikendr** [Apercu/react-native-zeroconf#36]
Hello,

First, thank you for providing this library. I have a use-case where i want to discover a node server on the local network. On the node server i tried using both [node_mdns](https://github.com/agnat/node_mdns) and [node-bonjur/zeroconf](https://github.com/watson/bonjour) for advertising the http server. On the mobile app i am scanning for such services using the `this._zeroconf.scan('http');` method, however, the http service does not seem to be discovered (events 'found' and 'resolved' do not get fired) from the mobile. I am using an android emulator btw.

Would really appreciate some feedback on this. Thank you!

**Comment by Apercu** [comment]
Hey ;)

Node mdns was also what I used in the past for my [remote control api](https://github.com/Apercu/furtive-api/blob/develop/index.js#L23), I would make sure your network allows your device to see each other, and that the service is running successfully. Are you able to discover your http server from another device with the node mdns browser methods?

**Comment by brikendr** [comment]
Thank you so much for your reply @Apercu 

Actually i have not tried to run browsing and advertising from two different devices yet, but i did run the mdn advertising service from one terminal and the discovery from another one, and it was successfully discovered (even node-bonjur was able to discover the mdns advertising service). I will try to run it from different devices and will report about the outcome. 

Thank you again for you answer.

**Comment by brikendr** [comment]
Another thing,

I checked my network settings and network discovery is enabled so i dont think there is something that prevents the discovery in this aspect. Or maybe there is something else i should check!!!

**Comment by Apercu** [comment]
Hum if you are not able to resolve it from the same device there's something weird then, I was thinking it was an issue with the network. Are you advertising over tcp?

**Comment by brikendr** [comment]
Here is my server code for advertising: 
`var ad = mdns.createAdvertisement(mdns.tcp('http'), 3000);
ad.start();`

The code from my react-native example app:
`constructor() {
    super();

    this._zeroconf = new Zeroconf();
    

    // Start the zeroconf scan using the huddlygo protocol
    this._zeroconf.on('update', () => {
      console.log("UPDATE! Services are: ",this._zeroconf.getServices());
    });
  }

  componentDidMount() {
    console.log('Component Mounted');
    
  }
  startDiscovery() {
    console.log('Starting Scan for HTTP Services');
    this._zeroconf.scan('http');
  }`
When i run the react-native app, the update event is fired, however, the service list is empty "{}". Other events such as "found" and "resolved" did not fire at all.

I am able to discover the advertised service when i use a normal terminal and the code snippet from either node-mdns: 
`var browser = mdns.createBrowser(mdns.tcp('http'));
browser.on('serviceUp', function(service) {
  console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
  console.log("service down: ", service);
});
browser.start();`

Or  with node-bonjour:
`var bonjour = require('bonjour')()

// browse for all http services
bonjour.find({ type: 'http' }, function (service) {
  console.log('Found an HTTP Go server:', service)
})`

**Comment by Apercu** [comment]
Could you add a `error` listener and see if it's called with a potential message? Also add `start`, `found` and `resolved`, to see if they are called

**Comment by brikendr** [comment]
@Apercu i tried your suggestions, unfortunately without any success. Here is the code:

```js
constructor() {
    super();

    this._zeroconf = new Zeroconf();
    
    this._zeroconf.on('update', () => {
      console.log("UPDATE! Services are: ",this._zeroconf.getServices());
    });

    
    this._zeroconf.on('found', () => {
      console.log("Found! Services are: ",this._zeroconf.getServices());
    });

    
    this._zeroconf.on('resolved', () => {
      console.log("Resolved! Services are: ",this._zeroconf.getServices());
    });
    
    this._zeroconf.on('error', (err) => {
      console.log("An error Occurred ",err);
    });
  }
  startDiscovery() {
    console.log('Starting Scan for HTTP Services');
    this._zeroconf.scan('http');
  }
```
I am not sure where the problem might be. Since it works from another terminal, i suppose it should work with the simulator as well. Is there any permissions i have to enable on the emulator to allow network discovery?

**Comment by Apercu** [comment]
Hum that's pretty much what I was [doing](https://github.com/Apercu/furtive-app/blob/develop/src/pages/MainPage.js#L32-L38) I'm not really sure now.. If you can try from another device and verify it's not the simulator or something blocking it, I don't remember any special setting

**Comment by brikendr** [comment]
Alright, anyway thank you for your effort :). Very much appreciate it.

**Comment by brikendr** [comment]
@Apercu i just have one more question. Did you test your projects/examples always using a real android device or you also tested using an emulator? And if you did test with an emulator, did it work? 

Thanks

**Comment by brikendr** [comment]
Hello @Apercu 

I tested the library with a real Android device and it is possible to discover the advertising http service. However, for some reason, when i reload the application, the service is not discovered anymore unless I rebuild the whole project. 

Is this an outcome of not properly stopping the scan service, or it might be something else. I also wanted to ask when is the best way of stopping the scanning of services! 

Thanks

**Comment by Apercu** [comment]
I usually do it in the. `componentWillUnmount` of the component that triggers the scan, but I'm not sure this will be called on reload, you might try it out ;)

**Comment by kimvex** [comment]
I have the same problem, and I can not solve it because I do not get back a single service.

**Comment by josvos** [comment]
Hi, on the emulator it doesn't work, probably because it uses some private address that is NAT'ed to the "real" network.  Websockets etc. work fine, but this discovery tool doesn't (exactly the same app on the same network does work fine on a real device).

**Comment by alejandromvp** [comment]
Please share the code of how to implement zeroconf and react native
