### ISSUE TITLE
Scan lan for available hosts

### ISSUE THREAD

**Issue by egorf** [Apercu/react-native-zeroconf#37]
Hi! 

Love the project. Works great. One question, is there a way to scan the local network for just hosts with advertised names? Say, none of the devices registered any services, however they are pingable by their .local name. Can I find them all?

**Comment by Apercu** [comment]
Hey! Thanks 😄 

That's a good question and given the actual implementation it's not possible. If you look at the [searchForServices](https://developer.apple.com/documentation/foundation/netservicebrowser/1417565-searchforservices), you need to provide a type and a domain for the scan, and it looks like the same for [Mono](http://www.mono-project.com/archived/monozeroconf/#documentation).

If you have control over the devices, you could register a dummy service just so you can discover them. There might be something else I don't know about, so I might still be wrong ;)

**Comment by egorf** [comment]
Thanks. I've also come to the same resolution after looking at various dns-sd and avahi docs
