### ISSUE TITLE
How to debug found, but not resolved services

### ISSUE THREAD

**Issue by egorf** [Apercu/react-native-zeroconf#38]
It's me again with another question. After building a small example with your library everything seemed find. Unfortunately, sometimes I get in a situation, when services get found, but never resolved. Could you give me a tip on how to investigate this?

**Comment by Apercu** [comment]
Hum weird, not really sure about that one never got the problem, sorry!
Will keep it open in case someone else has any idea or can reproduce

**Comment by egorf** [comment]
Never mind, seems like something was wrong on the service side. Sorry to bother

**Comment by egorf** [comment]
Well, I've only played around with this library for a couple of days. My problem was a combination of bad `dns-sd` parameters from the device side and an error in the 'resolved' handler. Unfortunately, most of the time, when something is wrong, JavaScript fails silently without really showing any signs of an error. That led me to believe something was wrong with the lib. 

Although, I have to say, it does not work as good, as, say, `avahi-discover -a`. I haven't had success turning the scan on and off more than one time(with corresponding handlers called) and I could not see new services appear and disappear immediately as they do with `avahi-discover`. I know this is only a wrapper around native APIs, so they problem is probably is quite deep. Will build a pure Java app to test this theory in the near future.
