### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by kimvex** [Apercu/react-native-zeroconf#39]
Hi, I have a problem when I want to scan and the error is as follows

Hello, I have a problem when I want to scan and the error is as follows

> [TypeError: undefined is not an object (evaluating 'RNZeroconf.scan')]

This is my code

```js
const zeroconf = new Zeroconf ();
Try {
  Zeroconf.scan (type = 'http', protocol = 'tcp', domain = 'local.');
} Catch (e) {console.log (e)}
```

What am I doing wrong?

**Comment by Apercu** [comment]
Hey, How's your import looking?

**Comment by kimvex** [comment]
I do it this way

import Zeroconf from 'react-native-zeroconf';

**Comment by Apercu** [comment]
Your scan should look like

```js
Zeroconf.scan();
Zeroconf.scan('http', 'tcp', 'local.'); // or something like this
```

You've copy-pasted the definition from the readme, this is not valid javascript.

**Comment by kimvex** [comment]
I have a question, can I find computers connected to my network with this module?

It is something that I am not clear, because it is what I am trying but the only thing that answers me is this

`{}`

in 

`Zeroconf.on('update', () => {
        console.log(Zeroconf.getServices());
})`

**Comment by Apercu** [comment]
You can if they advertise themselves using mdns or another zeroconf implementation.
