### ISSUE TITLE
Troubles getting the package to work

### ISSUE THREAD

**Issue by sosedoff** [Apercu/react-native-zeroconf#43]
Hey there,

I've been trying to get the react-native-zeroconf package to work. I pretty much followed your installation instructions on a brand new RN app (v0.47.2). Everything installed using `react-native install / link`. 

Here's some of my code:

```
import Zeroconf from 'react-native-zeroconf'
const zeroconf = new Zeroconf();

export default class App extends React.Component {
  componentDidMount() {
    console.log("Starting scan...");
    zeroconf.scan('http', 'tcp', 'local.');
  }
}
```

However, im getting the `undefined is not an object (evaluating 'RNZeroconf.scan`) error. Thinking something didnt link correctly, i ran `react-native eject` and followed the manual install from the wiki. That didnt fix anything. 

So not sure what im doing wrong. Any thoughts ?

**Comment by sosedoff** [comment]
NVM, the reason why nothing works is because i setup RN app with Expo, which does not support native modules. Bummer.

**Comment by Apercu** [comment]
I guess this should be closed then?

**Comment by sosedoff** [comment]
Yep
