### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by nomoreboredom** [Apercu/react-native-zeroconf#46]
Hey Apercu, 

Thanks for the library. 
Last year, this package came very handy to me while building an app.

This time, I have to use zeroconf again but still unsuccessful on the implementation until now, thats why I wanted to clarify/ask a couple of things.

Is this package supposed to be working on API below 21 on Android? 
The version I have used last time was 0.5.6, now I do see some NDS functions which are not supported below 21. Is this assumption correct?

Also, there isnt any mention of that I suppose but this package wont work on simulator or?

Thanks!

**Comment by Apercu** [comment]
Hello 😄 

We are now using the `getAttributes ` in order to get the TXT record of the device with https://github.com/Apercu/react-native-zeroconf/pull/44. I don't think it's supported on lower Android version, but it shouldn't break he whole process either. What's the error you are experiencing? Any stacktrace?

It should work in a simulator depending on your network settings and if you have devices advertising themselves on it.

**Comment by nomoreboredom** [comment]
So here is the thing.. I do have a dell printer on my network, which broadcasts its dns properly, I have no problem with that.

But we do have an iot device, which is connected via a lan cable to the router, and it 'only' broadcasts its name if the app is also connected to the router. When I connect the app to the Hotspot of this iot device, I do retrieve the data properly and no crash. But if I am connected to my router, I do only get the name broadcasted and the app crashes.

This is the log I see:

```2017-10-12 10:03:59.569 USNApp[8320:65123] -[NSNull bytes]: unrecognized selector sent to instance 0x108f8e180
2017-10-12 10:03:59.572 USNApp[8320:65123] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull bytes]: unrecognized selector sent to instance 0x108f8e180'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108cd1b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107b87141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108d41134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000108c58840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000108c583b8 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x0000000108c6270c CFStringCreateFromExternalRepresentation + 28
	6   Foundation                          0x0000000107669ad8 -[NSPlaceholderString initWithData:encoding:] + 115
	7   USNApp                              0x000000010713c9b6 +[RNNetServiceSerializer serializeServiceToDictionary:resolved:] + 1574
	8   USNApp                              0x000000010713bd46 -[RNZeroconf netServiceDidResolveAddress:] + 70
	9   CFNetwork                           0x0000000108663cb8 _ZL19_ShortTimerCallBackP16__CFRunLoopTimerPv + 88
	10  CoreFoundation                      0x0000000108c65454 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	11  CoreFoundation                      0x0000000108c650e3 __CFRunLoopDoTimer + 1011
	12  CoreFoundation                      0x0000000108c64caa __CFRunLoopDoTimers + 266
	13  CoreFoundation                      0x0000000108c5c9ec __CFRunLoopRun + 1916
	14  CoreFoundation                      0x0000000108c5c016 CFRunLoopRunSpecific + 406
	15  GraphicsServices                    0x000000010f0e9a24 GSEventRunModal + 62
	16  UIKit                               0x000000010b4d0134 UIApplicationMain + 159
	17  USNApp                              0x0000000106e9d06f main + 111
	18  libdyld.dylib                       0x000000010ce4165d start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) ```

Does these logs make any sense to you? Perhaps we can avoid some function call and avoid crash?

Thanks again for your help :)

**Comment by nomoreboredom** [comment]
I am closing this issue as I find out that the error is related to bad txt record object.

**Comment by Apercu** [comment]
Can you paste the txt record that was causing issues?
