### ISSUE TITLE
How to get TXT from bonjour service

### ISSUE THREAD

**Issue by drojas** [Apercu/react-native-zeroconf#9]
Hi, thanks for sharing this!

I'm trying to get the "txt" attribute from a bonjour service. See https://github.com/watson/bonjour

Do you have plans for supporting this?

**Comment by Apercu** [comment]
Is this specific to bonjour or all zeroconf implementations support it?

**Comment by drojas** [comment]
Apparently it is a feature described in DNS-based Service Discovery that happens to be implemented on bonjour (not sure about other implementations). I don't know the implications of that, but hope it can be opted in react-native-zeroconf.

Sources:
https://en.wikipedia.org/wiki/Zero-configuration_networking#DNS-based_service_discovery
http://www.zeroconf.org/rendezvous/txtrecords.html

**Comment by battuashwik** [comment]
@Apercu  adding support to export txtData into javascript resolved object.

https://github.com/Apercu/react-native-zeroconf/pull/30

**Comment by Apercu** [comment]
You can try the version published as of `0.7.1`, I'll keep this issue open since we don't have Android support yet.

**Comment by Apercu** [comment]
You can try the version published as of `0.7.1`, I'll keep this issue open since we don't have Android support yet.

**Comment by gcmartins93** [comment]
We have to discuss about android support and the NSDManager lib. As you can see [here](http://stackoverflow.com/questions/25984894/android-mdns-txt-record), NSDManager TXT records was only just added in API Level 21 (Android 5.0). Shall we keep using this library on android or just switch to JmDNS (even having a slower performance)?

**Comment by Apercu** [comment]
Maybe we can rely on [tinydnssd](https://github.com/youviewtv/tinydnssd) instead?

**Comment by gcmartins93** [comment]
I'm going to work on this, using tynydnssd instead.

**Comment by gcmartins93** [comment]
@Apercu adding support to txt attributes on android devices.

[#31](https://github.com/Apercu/react-native-zeroconf/pull/31)

**Comment by Apercu** [comment]
Added support for both Android & iOs in `0.8.0`
